### ISSUE TITLE
NoSuchMethodError when invoking PDF.ok()

### ISSUE THREAD

**Issue by Brazo** [benjohnde/play20-pdf#11]
Hello Jörg,

I get an exception when invoking PDF.ok() in my Controller with Play version 2.1 and Play-pdf version 0.4.1. 
Google indicates an issue between iText and Flying Saucer like here:
http://grails.1312388.n4.nabble.com/Grails-Rendering-Plugin-error-java-lang-NoSuchMethodError-com-lowagie-text-pdf-BaseFont-getCharBBox--td4525995.html

I appreciate any help or indications for a helpful source. 
Thanks a lot!

Build.scala:
"pdf" % "pdf_2.10" % "0.4.1",

resolvers += Resolver.url("Violas Play Modules", url("http://www.joergviola.de/releases/"))(Resolver.ivyStylePatterns)

Below is my exception:
[error] application - 

! @6dgga2n9a - Internal server error, for (GET) [/business/business-plan/result] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.NoSuchMethodError: com.lowagie.text.pdf.BaseFont.getCharBBox(C)[I]]
	at play.api.Application$class.handleError(Application.scala:289) ~[play_2.10.jar:2.1.0]
	at play.api.DefaultApplication.handleError(Application.scala:383) [play_2.10.jar:2.1.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2$$anonfun$handle$1.apply(PlayDefaultUpstreamHandler.scala:132) [play_2.10.jar:2.1.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2$$anonfun$handle$1.apply(PlayDefaultUpstreamHandler.scala:128) [play_2.10.jar:2.1.0]
	at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113) [play_2.10.jar:2.1.0]
	at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113) [play_2.10.jar:2.1.0]
java.lang.RuntimeException: java.lang.NoSuchMethodError: com.lowagie.text.pdf.BaseFont.getCharBBox(C)[I
	at play.libs.F$Promise$6.apply(F.java:401) ~[play_2.10.jar:2.1.0]
	at scala.concurrent.Future$$anonfun$map$1.liftedTree2$1(Future.scala:253) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) ~[scala-library.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) ~[scala-library.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.liftedTree1$1(BatchingExecutor.scala:67) ~[akka-actor_2.10.jar:na]
Caused by: java.lang.NoSuchMethodError: com.lowagie.text.pdf.BaseFont.getCharBBox(C)[I
	at org.xhtmlrenderer.pdf.ITextFontResolver$FontDescription.setMetricDefaults(ITextFontResolver.java:679) ~[core-renderer-R8.jar:na]
	at org.xhtmlrenderer.pdf.ITextFontResolver$FontDescription.<init>(ITextFontResolver.java:610) ~[core-renderer-R8.jar:na]
	at org.xhtmlrenderer.pdf.ITextFontResolver.addCourier(ITextFontResolver.java:410) ~[core-renderer-R8.jar:na]
	at org.xhtmlrenderer.pdf.ITextFontResolver.createInitialFontMap(ITextFontResolver.java:390) ~[core-renderer-R8.jar:na]
	at org.xhtmlrenderer.pdf.ITextFontResolver.<init>(ITextFontResolver.java:52) ~[core-renderer-R8.jar:na]
	at org.xhtmlrenderer.pdf.ITextRenderer.<init>(ITextRenderer.java:115) ~[core-renderer-R8.jar:na]

**Comment by Lonzak** [comment]
Actually **iText 2.1.7** is the last "free" version. "Free" in the sense of LPGL/MPL license (which was later changed to AGPL)
