### ISSUE TITLE
XHTML element with attribute "id" throws an error

### ISSUE THREAD

**Issue by teemoo7** [benjohnde/play20-pdf#17]
Hi, it sounds that since an element in the XHTML template has an "id" attribute, the PDF generation fails:

``` html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Test</title>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    </head>
    <body>
        <div id="wrapper">
            <p>Hello world</p>
        </div>
    </body>
</html>
```

Console log:

```
InputStream: Doctype given is "-//W3C//DTD XHTML 1.0 Transitional//EN"
InputStream: Document content looks like XHTML 1.0 Strict
no warnings or errors were found
ERREUR :  'NOT_FOUND_ERR: An attempt is made to reference a node in a context where it does not exist.'
[error] application - Creating document from template
org.xhtmlrenderer.util.XRRuntimeException: Can't load the XML resource (using TRaX transformer). org.w3c.dom.DOMException: NOT_FOUND_ERR: An attempt is made to reference a node in a context where it does not exist.
    at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:191) ~[core-renderer-R8.jar:na]
    at org.xhtmlrenderer.resource.XMLResource.load(XMLResource.java:79) ~[core-renderer-R8.jar:na]
    at util.pdf.PDF.toStream(PDF.java:186) [pdf_2.10-0.5.jar:0.5]
    at util.pdf.PDF.toBytes(PDF.java:168) [pdf_2.10-0.5.jar:0.5]
    at util.pdf.PDF.toBytes(PDF.java:145) [pdf_2.10-0.5.jar:0.5]
    at util.pdf.PDF.toBytes(PDF.java:140) [pdf_2.10-0.5.jar:0.5]
Caused by: javax.xml.transform.TransformerException: org.w3c.dom.DOMException: NOT_FOUND_ERR: An attempt is made to reference a node in a context where it does not exist.
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:732) ~[na:1.6.0_35]
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:336) ~[na:1.6.0_35]
    at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:189) ~[core-renderer-R8.jar:na]
    at org.xhtmlrenderer.resource.XMLResource.load(XMLResource.java:79) ~[core-renderer-R8.jar:na]
    at util.pdf.PDF.toStream(PDF.java:186) [pdf_2.10-0.5.jar:0.5]
    at util.pdf.PDF.toBytes(PDF.java:168) [pdf_2.10-0.5.jar:0.5]
Caused by: org.w3c.dom.DOMException: NOT_FOUND_ERR: An attempt is made to reference a node in a context where it does not exist.
    at org.apache.xerces.dom.ElementImpl.setIdAttributeNS(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
    at com.sun.org.apache.xalan.internal.xsltc.trax.SAX2DOM.startElement(SAX2DOM.java:201) ~[na:1.6.0_35]
    at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.closeStartTag(ToXMLSAXHandler.java:204) ~[na:1.6.0_35]
    at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.characters(ToXMLSAXHandler.java:524) ~[na:1.6.0_35]
    at org.apache.xerces.parsers.AbstractSAXParser.characters(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
    at org.apache.xerces.impl.dtd.XMLDTDValidator.characters(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
```

Since I remove the "id" attribute, it works out finely. The XHTML template above is valid given http://validator.w3.org/check

**Comment by eweiguu** [comment]
another way to work around is try to parse the xml document and then pass it to flying-saucer

**Comment by benjohnde** [comment]
I updated all the dependencies to the most recent version.
