### ISSUE TITLE
Unsupported font type under Debian Linux

### ISSUE THREAD

**Issue by irobert84** [benjohnde/play20-pdf#22]
Hi!

Windows with jvm 1.7.0_21 works fine, but under linux (jvm 1.6.0_26) i've got an excepion with this stack trace:

java.io.IOException: Unsupported font type
        at org.xhtmlrenderer.pdf.ITextFontResolver.addFont(ITextFontResolver.java:199) ~[core-renderer-R8.jar:na]
        at org.xhtmlrenderer.pdf.ITextFontResolver.addFont(ITextFontResolver.java:157) ~[core-renderer-R8.jar:na]
        at util.pdf.PDF.addFontDirectory(PDF.java:199) [pdf_2.10-0.5.jar:0.5]
        at util.pdf.PDF.toStream(PDF.java:180) [pdf_2.10-0.5.jar:0.5]
        at util.pdf.PDF.toBytes(PDF.java:168) [pdf_2.10-0.5.jar:0.5]
        at util.pdf.PDF.toBytes(PDF.java:145) [pdf_2.10-0.5.jar:0.5]
        at util.pdf.PDF.ok(PDF.java:135) [pdf_2.10-0.5.jar:0.5]
        at controllers.OrderController.renderStatusPdf(OrderController.java:380) [classes/:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$13$$anonfun$apply$13.apply(routes_routing.scala:257) [classes/:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$13$$anonfun$apply$13.apply(routes_routing.scala:257) [classes/:na]
        at play.core.Router$HandlerInvoker$$anon$6$$anon$2.invocation(Router.scala:175) [play_2.10.jar:2.1.2]
        at play.core.Router$Routes$$anon$1.invocation(Router.scala:355) [play_2.10.jar:2.1.2]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:50) [play_2.10.jar:2.1.2]
        at play.db.jpa.TransactionalAction$1.apply(TransactionalAction.java:19) [play-java-jpa_2.10.jar:2.1.2]
        at play.db.jpa.TransactionalAction$1.apply(TransactionalAction.java:17) [play-java-jpa_2.10.jar:2.1.2]
        at play.db.jpa.JPA.withTransaction(JPA.java:101) [play-java-jpa_2.10.jar:2.1.2]
        at play.db.jpa.TransactionalAction.call(TransactionalAction.java:14) [play-java-jpa_2.10.jar:2.1.2]
        at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:80) [play_2.10.jar:2.1.2]
        at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:79) [play_2.10.jar:2.1.2]
        at play.libs.F$Promise$PromiseActor.onReceive(F.java:425) [play_2.10.jar:2.1.2]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502) [akka-actor_2.10.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library.jar:na]

I'm trying arial, calibri and cambria

play version 2.1.2

Regards,
Róbert

**Comment by benjohnde** [comment]
Should be fixed. You need to deploy the font as well.
